
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    name: queue_demo
  exchange:
    name: exchange_demo
  routing:
    key: routing_key_demo

server:
  port: 8082