spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rpc:
  queue:
    name: rpc.queue
  reply:
    queue:
      name: rpc.rpc.reply.queue


server:
  port: 8081